name: clang
on: workflow_dispatch 

jobs:
  Download:
    name: 下载
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 下载
        run: curl https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-release/clang-r365631c.tar.gz -o clang-r365631c.tar.gz

      - name: 上传
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Release
          body: |
          
          files: |
            clang-r365631c.tar.gz
