name: 构建

env:
  kernel_repository: LineageOS/android_kernel_xiaomi_sdm845
  kernel_branch: lineage-22.1
  device: dipper
  clang_version: r365631c

on: workflow_dispatch


jobs:
  Build:
    name: 构建
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y binutils-arm-linux-gnueabi binutils-aarch64-linux-gnu

      - name: "AOSP-Clang: Restore"
        id: aosp_clang_restore
        uses: actions/cache/restore@v4
        with:
          path: aosp-clang
          key: aosp-clang-${{ env.clang_version }}

      - name: "AOSP-Clang: Download"
        id: aosp_clang_download
        if: steps.aosp_clang_restore.outputs.cache-hit != 'true'
        run: |
          mkdir aosp-clang
          curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-release/clang-r365631c.tar.gz | tar xz -C $GITHUB_WORKSPACE/aosp-clang

      - name: "AOSP-Clang: Save"
        id: aosp_clang_save
        if: steps.aosp_clang_download.outcome == 'success'
        uses: actions/cache/save@v4
        with:
          path: aosp-clang
          key: aosp-clang-${{ env.clang_version }}

      - name: AnyKernel3
        uses: actions/checkout@v4
        with:
          repository: osm0sis/AnyKernel3
          ref: master
          path: AnyKernel3

      - name: 同步本仓库
        uses: actions/checkout@v4
        with:
          path: this-repo

      - name: "Env: Setup"
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          chmod 777 $GITHUB_WORKSPACE/this-repo/bin/build.sh
          echo PATH=$GITHUB_WORKSPACE/this-repo/bin:$GITHUB_WORKSPACE/aosp-clang/bin:$PATH | tee -a $GITHUB_ENV

      - name: 同步内核源码
        uses: actions/checkout@v4
        with:
          repository: ${{ env.kernel_repository }}
          ref: ${{ env.kernel_branch }}
          path: kernel

      - name: 构建RissuKernelSU
        shell: bash
        run: build.sh "4.9.337-RissuKernelSU1.0.3-susfs1.5.5" "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" "susfs-v1.5.5" ""

      - name: 同步内核源码
        uses: actions/checkout@v4
        with:
          repository: ${{ env.kernel_repository }}
          ref: ${{ env.kernel_branch }}
          path: kernel

      - name: 构建KernelSUNext
        shell: bash
        run: build.sh "4.9.337-KernelSUNext1.0.3-susfs1.5.5" "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" "next-susfs" "susfs1.5.5-ksu-4.9.patch sucompat.c.diff"

      - name: 同步内核源码
        uses: actions/checkout@v4
        with:
          repository: ${{ env.kernel_repository }}
          ref: ${{ env.kernel_branch }}
          path: kernel

      - name: 构建KernelSU
        shell: bash
        run: build.sh "4.9.337-KernelSU0.9.5-susfs1.5.5" "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" "v0.9.5" "susfs1.5.5-ksu-4.9.patch susfs-ksu0.9.5.patch"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Release
          body: |
            设备：${{ env.device }}
            内核仓库：https://github.com/${{ env.kernel_repository }}
            分支：${{ env.kernel_branch }}

          files: |
            4.9.337-RissuKernelSU1.0.3-susfs1.5.5.zip
            4.9.337-KernelSUNext1.0.3-susfs1.5.5.zip
            4.9.337-KernelSU0.9.5-susfs1.5.5.zip
